version: '3'
services:
  db:
    build: ./database
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    command: sh -c "cd server && npm start"
    ports:
      - "3000:3000"
    links:
      - db