version: '3'
services:
  db:
    env_file:
      - .env
    build: ./database
  app:
    env_file:
      - .env
    environment:
      - DB_HOST=db
    build:
      context: ./
      dockerfile: Dockerfile
    command: sh -c "cd server && npm start"
    ports:
      - "3000:3000"
    links:
      - db